grid_map_topic: /elevation_mapping/traversability
occupancy_grid_topic: /mode3/roughness_cost
transform_layer: custom_traversability_roughness
# 是否要发布二值化的地图
get_01_value: false

# invalid_threshold
threshold: 80 #80
# 微调代价因子
downscale_cost_factor: 1
map_frame: "odom"
