grid_map_topic: /elevation_mapping/traversability
occupancy_grid_topic: /mode3/occupancy_grid
transform_layer:  custom_traversability_slope
# 是否要发布二值化的地图
get_01_value: false

# invalid_threshold
threshold: 70
# 微调代价因子
downscale_cost_factor: 0.5
map_frame: "odom"

# 左右设置无效边界,m
side_invalid_border: 1.0
# 这个位置前面全设为有效,m
front_all_valid_border: 1.0
# 后方设置无效边界,m
back_invalid_border: 2.0

# # 车的宽度,m
# car_width: 2.2
# # 车的长度,m
# car_length: 2.5
# 车的半径,m
car_radius: 0.55