#!/usr/bin/python3
import sys
# from navigation_gui.mypkg import MyPlugin
from rqt_gui.main import Main
from PyQt5.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QPushButton, QLabel
import PyQt5.QtCore as QtCore


plugin = 'navigation_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))